CREATE TABLE IF NOT EXISTS addresses(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS clients(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	full_name VARCHAR(50) NOT NULL,
	phone_number VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS drivers(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	age INT NOT NULL,
	rating NUMERIC(2) DEFAULT 5.5,
	
	CONSTRAINT chk_drivers_age_is_positive
	CHECK (age > 0)
);


CREATE TABLE IF NOT EXISTS cars(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	make VARCHAR(20) NOT NULL,
	model VARCHAR(20),
	year INT NOT NULL DEFAULT 1,
	mileage INT DEFAULT 1,
	condition CHAR(1) NOT NULL,
	category_id INT NOT NULL,
	
	CONSTRAINT chk_cars_year_is_positive
	CHECK (year > 0),
	
	CONSTRAINT chk_cars_mileage_is_positive
	CHECK (mileage > 0),
	
	FOREIGN KEY (category_id)
	REFERENCES categories(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS courses(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	from_address_id INT NOT NULL,
	start TIMESTAMP NOT NULL,
	bill NUMERIC(10, 2) DEFAULT 10,
	car_id INT NOT NULL,
	client_id INT NOT NULL,
	
	CONSTRAINT chk_courses_bill_is_positive
	CHECK (bill > 0),
	
	FOREIGN KEY (from_address_id)
	REFERENCES addresses(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	
	FOREIGN KEY (car_id)
	REFERENCES cars(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	
	FOREIGN KEY (client_id)
	REFERENCES clients(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS cars_drivers(
	car_id INT NOT NULL,
	driver_id INT NOT NULL,
	
	FOREIGN KEY (car_id)
	REFERENCES cars(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	
	FOREIGN KEY (driver_id)
	REFERENCES drivers(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);
